# Generated by Django 4.1.5 on 2023-01-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='product/'),
        ),
    ]
